version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3300:3300"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
