version: "3.9"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1s
      timeout: 2s
      retries: 10

  server:
      build:
        context: ./server
      env_file:
        - .env
      ports:
        - "${PORT}:${PORT}"
      volumes:
        - ./server:/app
      depends_on:
        db:
          condition: service_healthy

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
