version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
